trigger: none

jobs:
- job: Onnxruntime_Linux_GPU_Training_Perf_Test

  timeoutInMinutes: 120

  steps:
  - checkout: self
    clean: true
    submodules: recursive

  - script: >
      tools/ci_build/github/linux/run_dockerbuild.sh
      -o ubuntu16.04 -d gpu -r $(Build.BinariesDirectory)
      -x "
      --config RelWithDebInfo
      --enable_training
      --update --build
      "
    displayName: 'Build performance tests'

#
# scripts to run training test(s)
#
  - script: >
      docker rm -f "onnxruntime-gpu-perf" || true
    displayName: 'Remove perf container'

  - script: >
      docker run --gpus all -h OrtTrainingDev0 --name onnxruntime-gpu-perf 
      --volume $(Build.SourcesDirectory):/onnxruntime_src 
      --volume $(Build.BinariesDirectory):/build 
      --volume /bert_ort/bert_models:/build/bert_models:ro 
      --volume /bert_data:/build/bert_data:ro 
      -e NIGHTLY_BUILD onnxruntime-ubuntu16.04-cuda10.1-cudnn7.6
      /usr/bin/python3.6 "/onnxruntime_src/orttraining/tools/ci_test/run_bert_perf_test.py" 
      "--binary_dir" "/build/RelWithDebInfo" 
      "--training_data_root" "/build/bert_data" 
      "--model_root" "/build/bert_models"
    displayName: 'Run bert performance tests'

  # - script: >
  #     docker rm -f "onnxruntime-gpu-perf" || true
  #   displayName: 'Remove perf container'

#
# TODO scripts to generate jdbc.properties
#

#
# TODO scripts to maven build
#

#
# TODO scripts to run java
#

  - template: templates/clean-agent-build-directory-step.yml
